Display: added all the features from 3 files
AmateursLeague/sneaky-package pull request #119
Opened 2024-10-15 16:40 UTC by tannuiscoding

I have implemented the three `write.py`, `show.py` and `clip.py` in `display.py`.

2024-10-16 06:23 UTC, jindalpriyanshu101 requested changes
You're comparing different datatypes(string & int) as password check, fix that. i've attached 2 suggestions that you can implement to fix that.

2024-10-16 06:23 UTC, jindalpriyanshu101 commented on package/clip.py
> +    if int(password) != current_time:
This condition will never be true. as you're comparing int `password` with a string `current_time`
Consider typecasting `current_time` to int, OR don't typecast `password` 

```suggestion
    if int(password) != int(current_time):
```

OR Consider this:
```suggestion
    if password != current_time:
```

2024-10-16 06:23 UTC, jindalpriyanshu101 commented on package/show.py
> +    if int(password) != current_time:
same here

2024-10-16 06:23 UTC, jindalpriyanshu101 commented on package/write.py
> +    if int(password) != current_time:
same here as well

2024-10-16 20:57 UTC, jindalpriyanshu101 commented
The time is ticking 

![image](https://github.com/user-attachments/assets/4ff4d0c3-1c4d-439c-a1f5-8125764dde2a)

2024-10-17 04:40 UTC, this-is-yaash commented on package/show.py
> +    if int(password) != current_time:
```suggestion
    if int(password) != int(current_time):
```

2024-10-17 04:40 UTC, this-is-yaash commented on package/write.py
> +    if int(password) != current_time:
```suggestion
    if int(password) != int(current_time):
```

2024-10-17 04:43 UTC, this-is-yaash approved these changes
`display.py` feature is working perfectly. I have updated the arguments to accept `int` instead of `str`.

So far, LGTM! ✅

2024-10-17 04:44 UTC, this-is-yaash commented
fixes #77

2024-10-17 04:45 UTC, merged