fix: 🐛 Add create_clip
AmateursLeague/sneaky-package pull request #145
Opened 2024-10-21 18:44 UTC by yashksaini-coder

✅ Closes: #135

This pull request includes enhancements to the `package/clip.py` file by adding docstrings to improve code documentation and introduces a new asynchronous function in `package/create.py` to create and destroy clips with a specified lifetime.

### Documentation Improvements:

* Added docstrings to `display` function in `package/clip.py` to explain its purpose and usage.
* Added docstrings to `copy_to_clipboard` function in `package/clip.py` to describe its functionality and supported operating systems.

### New Feature:

* Introduced a new asynchronous `create` function in `package/create.py` to create and destroy clips on `cl1p.net`. The function includes nested asynchronous functions `create_clip` and `destroy_clip` and uses `asyncio` to manage the clip's lifetime.

---

[sneaky-package-135.webm](https://github.com/user-attachments/assets/1c0d573d-46e0-489c-836c-4d3658880173)

2024-10-21 18:44 UTC, yashksaini-coder commented
@jindalpriyanshu101 @ShashwatAgrawal20 @Wahid7852 @this-is-yaash review this PR, and also assign it to me

2024-10-21 19:05 UTC, ShashwatAgrawal20 requested changes
Please do the required changes.

2024-10-21 19:05 UTC, ShashwatAgrawal20 commented on package/create.py
> +asyncio.run(create('yash1', 'This clip will self-destruct!', 15))
ig this should be something like 
```suggestion
if __name__ == "__main__":
    asyncio.run(create('yash1', 'This clip will self-destruct!', 15))
```

2024-10-21 19:05 UTC, ShashwatAgrawal20 commented on package/create.py
I guess you can also remove those comments, those seems way too obvious tbh!

2024-10-21 19:05 UTC, ShashwatAgrawal20 commented on package/create.py
> +        print("Failed to create the clip.")
And ig you can also do some exception handling and stuff too, maybe some try/except blocks.

2024-10-21 20:04 UTC, yashksaini-coder commented
hi @ShashwatAgrawal20 i have done the changes and logging off now. Let me know the status tomorrow

2024-10-22 07:56 UTC, this-is-yaash reviewed
The implementation works well!🚀

But from what I've noticed, the duration limit is kind of odd (im not sure abt the right term).

```py
asyncio.run(create('letstestthis', 'This clip will self-destruct!', 5))
```
When I pass this args, I noticed certain behaviours:
- The site is available for only 5 seconds ✅
- It's unavailable, if I open after 5 seconds ✅ 

These are good, and implemented well.

But apart from the above mentioned:
- When I visit the link and refresh the page within 5 seconds, it resets again ❌.

In simple terms, it utilized more than one view options
- view once.
- view once within time limit 
> from my observations

I'll give you an overview of how to implement them (duration part).
In the site we have **7 view options**:
![image](https://github.com/user-attachments/assets/8cce39d7-2256-4852-af47-09b7bb028d5d)
1. Set the **View Once** (1st option) as the default (no need to mention the arguments).
2. Use `int` to match the view options.
3. `create("link", 1)` represents the 2nd option (1 Minute), and vice versa. 

What I'm trying to say is that try to match the given option with `int`. We basically made "**View Once**" default. So 2nd option is 1 minute -> pair it with `int 1`. 3rd option is 10 minutes -> pair it with `int 2`.

This is what I thought of implementing it rather than ending the duration within seconds.

If you have better approach, please let me know.
But what I need is that, I want you implement the duration part with the 7 options we have. (we don't need to mention the duration ourselves).

2024-10-22 07:56 UTC, this-is-yaash commented on package/clip.py
> +    """
```suggestion
```

2024-10-22 07:56 UTC, this-is-yaash commented on package/clip.py
> +    """
```suggestion
```
uncomment!

2024-10-22 13:05 UTC, yashksaini-coder commented
@this-is-yaash review this PR now

2024-10-22 18:48 UTC, Wahid7852 approved these changes
LGTM

2024-10-23 04:01 UTC, this-is-yaash reviewed
"Duration" logic is implemented well. However, the **texts inside the site resets** when I reload the page.

Can you find a way to fix that?

2024-10-23 04:28 UTC, this-is-yaash commented
"@yashksaini-coder, I'm merging this PR. Although the result is somewhat broken (using **view once mode with a custom time limit**), I hope we can find a way to fix it in the future. For now, I'll merge this PR as it has accomplished what was mentioned in issue #135

2024-10-23 04:29 UTC, merged

2024-10-23 04:38 UTC, yashksaini-coder commented
> "@yashksaini-coder, I'm merging this PR. Although the result is somewhat broken (using **view once mode with a custom time limit**), I hope we can find a way to fix it in the future. For now, I'll merge this PR as it has accomplished what was mentioned in issue #135 

Yeah just give me few days will figure out something

2024-10-23 04:43 UTC, yashksaini-coder commented
@this-is-yaash bro can you add labels on this PR