added snippet_utils.py
AmateursLeague/sneaky-package pull request #56
Opened 2024-10-03 05:46 UTC by KirtiPratihar

This Python code provides utility functions for managing code snippets stored in a "code_snippets" directory. The script includes three key functionalities:

1.**display(snippet_name):**- Reads and prints the content of a Python file (a code snippet) in the console.
The snippet file is located in a subfolder called "code_snippets", and its name is passed as an argument (snippet_name). 

2.**copy_to_clipboard(snippet_name):**-Copies the content of the specified snippet file to the system clipboard.
The function supports different platforms:
For Linux: It uses the xclip command.
For Windows: It uses the clip.exe command.
Other platforms are not supported, and it raises an OSError for unsupported operating systems.

3.**write_to_root(snippet_name):**-Writes the content of the snippet file to the root directory where the script is executed.
The file is saved with the same name as the snippet but in the current working directory instead of the "code_snippets" folder.

2024-10-03 06:57 UTC, jindalpriyanshu101 commented on snippet_utils.py
> +#     main()
Why?

2024-10-03 07:10 UTC, jindalpriyanshu101 commented
I don't understand the context? what `code_snippets` directory are you talking about? and why you created this `snippet_utils.py`

Also, do link the issue which you're solving.

2024-10-03 11:17 UTC, KirtiPratihar commented
this is the issue which was assigned- **https://github.com/AmateursLeague/sneaky-package/issues/21** and as solution, I have made **snippet_utils.py** , so that we can asscess everything from one .

In simple terms, instead of calling 3 features separately, we’ll call the methods separately from one file.

2024-10-03 13:04 UTC, Wahid7852 commented
Hi Kirti, can you update your code? We have support for macOS as well and updated functionality in the files, so please do the necessary.

2024-10-03 15:05 UTC, this-is-yaash reviewed
I have noted 6 changes, please make necessary updates!
Additionally change the filename to `display.py`

2024-10-03 15:05 UTC, this-is-yaash commented on snippet_utils.py
> +def copy_to_clipboard(snippet_name):
```suggestion
def graph(snippet_name):
```

2024-10-03 15:05 UTC, this-is-yaash commented on snippet_utils.py
> +def write_to_root(snippet_name):
```suggestion
def piechart(snippet_name):
```

2024-10-03 15:05 UTC, this-is-yaash commented on snippet_utils.py
> +def display(snippet_name):
```suggestion
def models(snippet_name):
```

2024-10-03 15:05 UTC, this-is-yaash commented on snippet_utils.py
> +#     main()
Remove these lines as well!

2024-10-03 15:50 UTC, jindalpriyanshu101 requested changes

2024-10-03 15:50 UTC, jindalpriyanshu101 commented on snippet_utils.py
> +    """
Remove these comments

2024-10-03 17:55 UTC, jindalpriyanshu101 approved these changes
LGTM, Approved as requested changes are implemented.

2024-10-04 02:46 UTC, this-is-yaash approved these changes
LGTM!
Good job!

2024-10-04 02:46 UTC, merged

2024-10-04 02:48 UTC, this-is-yaash commented
@KirtiPratihar Star⭐ this repo if you like it!
Thanks your contributions!