Implement dynamic password protection for snippet access
AmateursLeague/sneaky-package pull request #60
Opened 2024-10-03 18:07 UTC by Varun-malviya5

Fixes #14
This Pull Request implements a password protection feature for accessing Python snippet files stored in the stash directory. The password changes dynamically based on the current time (HHMM format).

Changes Made:

models.py:

Added the display function that verifies a password against the current time before allowing access to snippet files. If the password is incorrect, access is denied.
graph.py:

Implemented a function to copy text to the clipboard, supporting multiple operating systems (Linux, Windows, macOS).
piechart.py:

Modified to include functionality for writing the contents of a snippet file to the root directory, ensuring the files can be saved directly from the application.
test_display.py:

Created a test file to verify the functionality of the password protection in the display function, ensuring correct handling of valid and invalid passwords.

2024-10-03 18:23 UTC, Wahid7852 commented on python
why is this file existing?

2024-10-03 18:29 UTC, jindalpriyanshu101 requested changes
I have added 5 comments, please responded to them accordingly.

Also, What kind of password protection are you trying to implement??? Due to this, user would have to enter current Hour and Minute as password, And boom they'll get access.

2024-10-03 18:29 UTC, jindalpriyanshu101 commented on package/graph.py
> +    return datetime.now().strftime('%H%M')
Explain this.

2024-10-03 18:29 UTC, jindalpriyanshu101 commented on package/graph.py
> +        print(f"Error: {e}")
utilize shutil for file checks, don't add whole code into `try-except` block

2024-10-03 18:29 UTC, jindalpriyanshu101 commented on package/models.py
> +
Explain this too

2024-10-03 18:29 UTC, jindalpriyanshu101 commented on package/piechart.py
> +    return datetime.now().strftime('%H%M')
Explain

2024-10-03 18:29 UTC, jindalpriyanshu101 commented on package/test_display.py
> +    test_display_function()
Can you explain why you created this? `snippet_name` is expected to be changed dynamically by user inputs.

Also, explain the logic you used for defining `correct_password` and the test case with `incorrect_password` i don't understand why its added? its not needed.

2024-10-03 18:38 UTC, jindalpriyanshu101 commented
And, also resolve these merge conflicts. @Varun-malviya5

2024-10-04 10:24 UTC, this-is-yaash commented
@Varun-malviya5 any updates on this PR?

2024-10-05 08:56 UTC, closed without merging